# Generated by Django 5.2.1 on 2025-06-26 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relattionship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('from_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_from', to='planner.guest')),
                ('to_guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships_to', to='planner.guest')),
            ],
            options={
                'unique_together': {('from_guest', 'to_guest')},
            },
        ),
    ]
